DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID SMALLINT ,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP ,
    PRICE_LIST INTEGER ,
    PRODUCT_ID INTEGER ,
    PRIORITY SMALLINT ,
    PRICE NUMERIC(20,2) ,
    CURR VARCHAR
);
